# Generated by Django 5.1.4 on 2025-05-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_producto_categoria_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_ruta',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='default.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
