# Generated by Django 5.2.1 on 2025-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marca_proveedor_tipousuario_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_id',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Gestor de Inventario'), (2, 'Comprador'), (3, 'Encargado de Logística'), (4, 'Jefe de Producción'), (5, 'Auditor de Inventario'), (6, 'Gerente de Proyectos'), (7, 'Trabajador de Planta')], default=0),
        ),
    ]
