# Generated by Django 5.2.1 on 2025-06-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_producto_precio_remove_usuario_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor'),
        ),
    ]
