# Generated by Django 5.2.1 on 2025-06-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_ordencompra_usuario_ordencompra_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='productos',
        ),
        migrations.CreateModel(
            name='ProductoOrdenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor_id', models.IntegerField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='myapp.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
    ]
