# Generated by Django 5.2.1 on 2025-06-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ordencompra_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoordenado',
            name='nombre_producto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productoordenado',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productoordenado',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productoordenado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
