# Generated by Django 5.2.1 on 2025-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_proveedor_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_id',
            field=models.IntegerField(choices=[(-1, 'Deshabilitado'), (0, 'Administrador'), (1, 'Gestor de Inventario'), (2, 'Comprador'), (3, 'Encargado de Logística'), (4, 'Jefe de Producción'), (5, 'Auditor de Inventario'), (6, 'Gerente de Proyectos'), (7, 'Trabajador de Planta')], default=7),
        ),
    ]
